apiVersion: cilium.io/v1alpha1
kind: CiliumConfig
metadata:
  name: cilium
  namespace: cilium
spec:
  operator:
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
  hubble:
    enabled: true
    metrics:
      enabled:
        - 'dns:labelsContext=source_namespace,destination_namespace'
        - 'drop:labelsContext=source_namespace,destination_namespace'
        - 'tcp:labelsContext=source_namespace,destination_namespace'
        - 'icmp:labelsContext=source_namespace,destination_namespace'
        - port-distribution
        - >-
          flow:labelsContext=source_namespace,destination_namespace;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity
        - >-
          kafka:labelsContext=source_namespace,source_workload,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity
        - >-
          httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity
      serviceMonitor:
        enabled: true
    relay:
      enabled: true
    tls:
      enabled: false
    ui:
      enabled: true
  ipv6:
    enabled: true
  prometheus:
    serviceMonitor:
      enabled: false
  securityContext:
    privileged: true
  ipam:
    mode: cluster-pool
    operator:
      clusterPoolIPv4PodCIDRList:
        - 10.216.0.0/14
  cni:
    binPath: /var/lib/cni/bin
    confPath: /var/run/multus/cni/net.d
  sessionAffinity: true